services:
  db:
    image: postgres:18-alpine
    container_name: expense-tracker-fastapi
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
